### ISSUE TITLE
ERROR: Can't figureout desktop environment

### ISSUE THREAD

**Issue by attinderdhillon** [Rishang/gnome-theme-installer#1]
Same message again and again.

`gnomelooks -i https://www.gnome-look.org/p/1246387
ERROR: Can't figureout desktop environment
Which one is your desktop environment 

id| Name
--+-------
 1| Gnome
 2| Kde
 3| Xfce

Enter id for your desktop environment: 1
`

**Comment by Rishang** [comment]
It searches for key "gnome", "kde" or "xfce" in /proc/sched_debug in order identify the gtk theme directory.

**Comment by Rishang** [comment]
i have update the code to fix this issue pull it by `cd ~/.gnomelooks; git pull`
